### ISSUE TITLE
spython excecution

### ISSUE THREAD

**Issue by rafalohaki** [nirajxhrestha/NITRO-GEN-AND-CHECKER-V2#1]
i have a small problem.
when i try to run it i get error:
File "main.py", line 12
    print(f"{Fore.WHITE}[ {Fore.CYAN}§ {Fore.WHITE}] {Fore.LIGHTBLACK_EX}Discord Nitro Generator By {Fore.WHITE}XDWOLF{Fore.LIGHTBLACK_EX} | Licensed under {Fore.WHITE}MIT {Fore.LIGHTBLACK_EX}License")

**Comment by rafalohaki** [comment]
i installed req

**Comment by nirajxhrestha** [comment]
pip install these two inside main.py folder
colorama==0.4.3
requests==2.24.0
